apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: pod-gpu-metrics-exporter
  name: pod-gpu-metrics-exporter
  namespace: monitoring
spec:
  ports:
  - name: metric
    port: 9400
    targetPort: 9400
  selector:
    app: pod-gpu-metrics-exporter