apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-gpu-metrics-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pod-gpu-metrics-exporter
  template:
    metadata:
      labels:
        app: pod-gpu-metrics-exporter
      name: pod-gpu-metrics-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tmax/gpudriver
                operator: In
                values:
                - 'nvidia'
      containers:
      - image: nvidia/dcgm-exporter:2.1.4-2.2.0-ubuntu18.04
        name: nvidia-dcgm-exporter
        ports:
        - name: gpu-metrics
          containerPort: 9400
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
            add: ["CAP_SETFCAP", "SYS_ADMIN"]
      volumes:
      - name: device-metrics
        emptyDir:
          medium: Memory