apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: pod-gpu-metrics-exporter
  name: pod-gpu-metrics-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: metric
    path: /gpu/metrics
  selector:
    matchLabels:
      k8s-app: pod-gpu-metrics-exporter